apply plugin: 'com.android.library'
apply plugin: 'expo-module-gradle-plugin'

group = 'com.wapve.credentials'
version = '0.1.0'

android {
  namespace 'com.wapve.credentials'
  defaultConfig {
    minSdkVersion 28
    versionCode 1
    versionName '0.1.0'
  }
}

dependencies {
  implementation 'androidx.credentials:credentials:1.6.0'
  implementation 'androidx.credentials:credentials-play-services-auth:1.6.0'
}
